name: Test

on:
  workflow_dispatch:
    inputs:
      message:
        description: 'Log level'
        required: true
        default: 'warning'

jobs:
  printInputs:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: My first step
        uses: ./.github/actions/my-action
        with:
          message: ${{ github.event.inputs.message }}
