name: Manual publish
on:
  workflow_dispatch:
    inputs:
      version:
        description: '1.2.3'
        required: true
    branches:
      - master
jobs:
  publish:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [14]
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
      - run: echo "Release v${{ github.event.inputs.version }}"
      - name: Checkout release branch
        run: |
          git config --global user.name "${{ github.actor }}"
          git config --global user.email "${email}"
          git checkout -b release/${{ github.event.inputs.version }} origin/master
          git push --set-upstream origin release/${{ github.event.inputs.version }}
      - run: npm ci
      - run: npm run build
      - name: Set version
        run: npm run version -- "${{ github.event.inputs.version }}" --yes
      - name: 'publish'
        run: |
          echo "//registry.npmjs.org/:_authToken=${{ secrets.NPM_PUBLISH_TOKEN }}" > ./.npmrc
          npm whoami
          npm run publish -- --yes
          git push
