name: Publish
on:
  workflow_dispatch:
    inputs:
      version:
        description: '1.2.3'
        required: true
jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - run: npm ci
      - run: npm run build
      - name: 'publish'
        run: |
          cd packages/ts-transpiler
          echo "//registry.npmjs.org/:_authToken=${{ secrets.NPM_PUBLISH_TOKEN }}" > ./.npmrc
          npm version v${{ github.event.inputs.version }}
          npm publish
